### ISSUE TITLE
Plugin breaks VSR

### ISSUE THREAD

**Issue by 6hundred9** [thecroshel/JoinLogger#1]
![image](https://github.com/user-attachments/assets/ec2f4fb4-cdaf-4bc0-8185-bc63243e5500)

![image](https://github.com/user-attachments/assets/5608a9f8-0c54-4328-9606-aba731af6ef7)

You need to add a check whether the player has DNT or not and if they have DNT you must ask them for privilege to track which they can agree by, for example, running a command

**Comment by thecroshel** [comment]
sadece ip logumu sıkıntı oluşturuyor eğer öyleyse onu siliyim

**Comment by 6hundred9** [comment]
gerek yok la
